CREATE TABLE IF NOT EXISTS authors (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS book (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    publish_time TIMESTAMP NOT NULL
);
